# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cf2dc4241e29f56f93884c556b3210ffb03bbfdb6e8c9226c2c5b7f176c06f99e2140e2d079a9b60ea1d865c2c2b1f0168e469229716a4d7ad30084a4c76933

test:
  secret_key_base: fef8c4b45eb14a31728f33a9dab3332f4a0ce0c316304a9b8d6405a9e215e19afa3ef7cea35dfe280473d69c6194ddc730279ad5971973b91ce3acf244063015

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
